sudo: false
language: node_js

node_js:
  - 'stable'
  - '4'
  - '0.12'

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-p-cli' ]; then cd .. && eval "mv $currentfolder generator-p-cli" && cd generator-p-cli; fi
