sudo: false
language: node_js

node_js:
  - 'iojs'
  - '0.12'
  - '0.11'
  - '0.10'

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-p' ]; then cd .. && eval "mv $currentfolder generator-p" && cd generator-p; fi
